[mypy]
python_version = 3.13
strict = False
check_untyped_defs = True
ignore_missing_imports = True
exclude = ^common/
plugins = sqlalchemy.ext.mypy.plugin, pydantic.mypy

[mypy-aio_pika.*]
ignore_missing_imports = True

[mypy-asyncpg.*]
ignore_missing_imports = True

[mypy-loguru.*]
ignore_missing_imports = True

[mypy-common.*]
ignore_errors = True